import { createPostprocessPass } from "../../render/postprocess.js?v=20260803-7";
import { resizeCanvasToDisplaySize } from "../../render/webgl.js?v=20260803-7";
const fragmentSource=`#version 300 es
precision highp float; uniform float uSegments; uniform float uSilhouette; uniform int uView; in vec2 vUv; out vec4 outColor;
float polygonRadius(float angle,float sides){float sector=6.2831853/sides;return cos(3.14159265/sides)/cos(mod(angle+sector*0.5,sector)-sector*0.5);}
vec3 renderLod(vec2 q,float sides,bool reference){float angle=atan(q.y,q.x);float circleR=length(q);float poly=polygonRadius(angle,sides);float boundary=poly*0.72;float inside=1.0-smoothstep(boundary-0.012,boundary+0.012,circleR);float z=sqrt(max(1.0-pow(circleR/max(boundary,0.01),2.0),0.0));float facet=floor((angle/6.2831853+0.5)*sides)/sides;vec3 normal=normalize(vec3(cos(facet*6.2831853)*sqrt(1.0-z*z),sin(facet*6.2831853)*sqrt(1.0-z*z),z));float light=0.2+max(dot(normal,normalize(vec3(-0.5,0.8,0.6))),0.0);vec3 surface=mix(vec3(0.05,0.24,0.21),vec3(0.22,0.88,0.68),light);float radial=1.0-smoothstep(0.012,0.035,abs(fract((angle/6.2831853+0.5)*sides)-0.5));float rings=1.0-smoothstep(0.015,0.04,abs(fract(circleR/max(boundary,0.01)*max(3.0,sides*0.3))-0.5));float wire=max(radial,rings)*inside;float error=abs(0.72-boundary)*22.0;vec3 heat=mix(vec3(0.08,0.65,0.75),vec3(1.0,0.18,0.05),clamp(error,0.0,1.0));if(uView==1)surface=mix(vec3(0.025),vec3(0.20,0.95,0.78),wire);if(uView==2)surface=heat;float referenceRing=(1.0-smoothstep(0.006,0.015,abs(circleR-0.72)))*uSilhouette;surface=mix(surface,vec3(0.96,0.72,0.28),referenceRing*(reference?0.0:1.0));return surface*inside+referenceRing*vec3(0.96,0.72,0.28);}
void main(){vec2 p=(vUv*2.0-1.0)*vec2(1.62,1.0);vec3 bg=mix(vec3(0.018,0.026,0.029),vec3(0.08,0.12,0.13),vUv.y);vec2 left=p-vec2(-0.78,0.0),right=p-vec2(0.78,0.0);vec3 a=renderLod(left,32.0,true),b=renderLod(right,uSegments,false);float ma=step(length(left),0.78),mb=step(length(right),0.78);vec3 color=bg+a*ma+b*mb;float split=1.0-smoothstep(0.0,0.006,abs(p.x));color+=split*vec3(0.18,0.30,0.29);outColor=vec4(pow(max(color,vec3(0)),vec3(1.0/2.2)),1.0);}`;
const state={distance:360,segments:18,silhouette:70,tolerance:110,view:"surface"};const ui={canvas:document.querySelector("#lodCanvas"),distance:document.querySelector("#lodDistance"),distanceValue:document.querySelector("#lodDistanceValue"),effective:document.querySelector("#lodEffective"),error:document.querySelector("#lodError"),guideError:document.querySelector("#lodGuideError"),guideSelected:document.querySelector("#lodGuideSelected"),ratio:document.querySelector("#lodRatio"),section:document.querySelector("#mesh-lod"),segments:document.querySelector("#lodSegments"),segmentsValue:document.querySelector("#lodSegmentsValue"),silhouette:document.querySelector("#lodSilhouette"),silhouetteValue:document.querySelector("#lodSilhouetteValue"),tolerance:document.querySelector("#lodTolerance"),toleranceValue:document.querySelector("#lodToleranceValue"),triangles:document.querySelector("#lodTriangles"),view:document.querySelector("#lodView")};
function selectedSegments(){const projected=state.segments*(3.6/(state.distance/100))/Math.sqrt(state.tolerance/100);return Math.max(4,Math.min(state.segments,Math.round(projected*(0.7+state.silhouette/250))));}
class Renderer{constructor(c){this.canvas=c;this.gl=c.getContext("webgl2",{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error("当前浏览器不支持 WebGL2。");this.pass=createPostprocessPass(this.gl,fragmentSource);this.loc={segments:this.gl.getUniformLocation(this.pass.program,"uSegments"),silhouette:this.gl.getUniformLocation(this.pass.program,"uSilhouette"),view:this.gl.getUniformLocation(this.pass.program,"uView")};}render(s){const gl=this.gl,{width,height}=resizeCanvasToDisplaySize(this.canvas);this.pass.draw({configure:()=>{gl.uniform1f(this.loc.segments,selectedSegments());gl.uniform1f(this.loc.silhouette,s.silhouette/100);gl.uniform1i(this.loc.view,{surface:0,wire:1,error:2}[s.view]);},width,height});}}
function fail(m){ui.section?.classList.add("is-unavailable");const p=document.createElement("p");p.className="webgl-fallback";p.textContent=`LOD 实验无法启动：${m}`;ui.canvas?.closest(".viewport-panel")?.prepend(p);}export function initMeshLodLab(){if(!ui.canvas||!ui.view)return;let r;try{r=new Renderer(ui.canvas);}catch(e){fail(e.message);return;}let f=0;const render=()=>{f=0;r.render(state);const n=selectedSegments(),tri=n*n*2,full=state.segments*state.segments*2,error=state.tolerance/100;ui.segmentsValue.value=`${state.segments} 环`;ui.distanceValue.value=`${(state.distance/100).toFixed(2)} m`;ui.toleranceValue.value=`${error.toFixed(2)} px`;ui.silhouetteValue.value=`${state.silhouette}%`;ui.effective.textContent=`${n} 环`;ui.triangles.textContent=tri.toLocaleString("zh-CN");ui.error.textContent=`${error.toFixed(2)} px`;ui.ratio.textContent=`${Math.round((1-tri/full)*100)}%`;ui.guideSelected.textContent=`${n} 环`;ui.guideError.textContent=`${error.toFixed(2)} px`;};const schedule=()=>{if(!f)f=requestAnimationFrame(render);};[[ui.view,"change","view",String],[ui.segments,"input","segments",Number],[ui.distance,"input","distance",Number],[ui.tolerance,"input","tolerance",Number],[ui.silhouette,"input","silhouette",Number]].forEach(([e,n,k,c])=>e.addEventListener(n,()=>{state[k]=c(e.value);schedule();}));addEventListener("resize",schedule);render();}
