import { createPostprocessPass } from "../../render/postprocess.js?v=20260803-10";
import { resizeCanvasToDisplaySize } from "../../render/webgl.js?v=20260803-10";

const fragmentSource=`#version 300 es
precision highp float;
uniform float uTargets; uniform float uSamples; uniform float uOverdraw; uniform float uCompression; uniform int uPattern;
in vec2 vUv; out vec4 outColor;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
void main(){vec2 cells=vec2(18.0,11.0);vec2 id=floor(vUv*cells),local=fract(vUv*cells);float border=step(0.08,min(min(local.x,local.y),min(1.0-local.x,1.0-local.y)));float h=hash(id);float enabled=0.0;vec3 work=vec3(0.18,0.78,0.67);
  if(uPattern==0)enabled=1.0-smoothstep(1.4,2.4,abs(id.y-(id.x*0.48+2.0)));
  else if(uPattern==1){enabled=step(0.72,h);work=vec3(0.42,0.56,0.95);}
  else if(uPattern==2){vec2 p=vUv-vec2(0.5);float rings=0.5+0.5*sin(length(p)*75.0*uOverdraw);enabled=smoothstep(0.2,0.8,rings);work=mix(vec3(0.96,0.33,0.12),vec3(1.0,0.74,0.18),h);}
  else{float front=step(h,0.44);enabled=front;work=front>0.5?vec3(0.18,0.82,0.67):vec3(0.28,0.31,0.31);}
  vec3 color=mix(vec3(0.025,0.035,0.04),vec3(0.085,0.10,0.11),vUv.y);color=mix(color,work,enabled*border*(0.45+0.35*uTargets));float cacheBand=1.0-smoothstep(0.0,0.018,abs(vUv.y-(0.13+0.06*sin(vUv.x*22.0+(uPattern==1?h*8.0:0.0)))));color=mix(color,vec3(0.95,0.63,0.18),cacheBand*(uPattern==2?0.85:0.38));float compression=step(0.97,fract((vUv.x+vUv.y)*38.0*uCompression));color+=compression*vec3(0.08,0.16,0.15);outColor=vec4(pow(max(color,vec3(0)),vec3(1.0/2.2)),1.0);}`;
const state={pattern:"prepass",targets:3,samples:2,overdraw:36,compression:42};
const ui={bytes:document.querySelector("#bandwidthBytes"),canvas:document.querySelector("#bandwidthCanvas"),compression:document.querySelector("#bandwidthCompression"),compressionValue:document.querySelector("#bandwidthCompressionValue"),frameMetric:document.querySelector("#bandwidthFrame"),hitRate:document.querySelector("#bandwidthHitRate"),overdraw:document.querySelector("#bandwidthOverdraw"),overdrawValue:document.querySelector("#bandwidthOverdrawValue"),pattern:document.querySelector("#bandwidthPattern"),rate:document.querySelector("#bandwidthRate"),samples:document.querySelector("#bandwidthSamples"),samplesValue:document.querySelector("#bandwidthSamplesValue"),section:document.querySelector("#bandwidth-cache"),strip:[...document.querySelectorAll(".bandwidth-stage-strip [data-pattern]")],targets:document.querySelector("#bandwidthTargets"),targetsValue:document.querySelector("#bandwidthTargetsValue")};
function model(){const pattern={coherent:{hit:.91,work:1},random:{hit:.42,work:1.42},overdraw:{hit:.68,work:state.overdraw/10},prepass:{hit:.86,work:1+state.overdraw/42}}[state.pattern];const compression=1-state.compression/100;const bytes=(state.targets*4+4)*state.samples*pattern.work*compression;const mb=bytes*2.07e6/1e6;return{bytes,mb,hit:pattern.hit,rate:mb*120/1000};}
class Renderer{constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl2",{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error("当前浏览器不支持 WebGL2。");this.pass=createPostprocessPass(this.gl,fragmentSource);this.loc={compression:this.gl.getUniformLocation(this.pass.program,"uCompression"),overdraw:this.gl.getUniformLocation(this.pass.program,"uOverdraw"),pattern:this.gl.getUniformLocation(this.pass.program,"uPattern"),samples:this.gl.getUniformLocation(this.pass.program,"uSamples"),targets:this.gl.getUniformLocation(this.pass.program,"uTargets")};}render(s){const gl=this.gl,{width,height}=resizeCanvasToDisplaySize(this.canvas);this.pass.draw({configure:()=>{gl.uniform1f(this.loc.targets,s.targets/5);gl.uniform1f(this.loc.samples,s.samples/4);gl.uniform1f(this.loc.overdraw,s.overdraw/10);gl.uniform1f(this.loc.compression,s.compression/10);gl.uniform1i(this.loc.pattern,{coherent:0,random:1,overdraw:2,prepass:3}[s.pattern]);},width,height});}}
function fail(message){ui.section?.classList.add("is-unavailable");const p=document.createElement("p");p.className="webgl-fallback";p.textContent=`带宽缓存实验无法启动：${message}`;ui.canvas?.closest(".viewport-panel")?.prepend(p);}
export function initBandwidthCacheLab(){if(!ui.canvas||!ui.pattern)return;let renderer;try{renderer=new Renderer(ui.canvas);}catch(error){fail(error.message);return;}let frame=0;const render=()=>{frame=0;renderer.render(state);const m=model();ui.targetsValue.value=`${state.targets} × RGBA8`;ui.samplesValue.value=`${state.samples}×`;ui.overdrawValue.value=`${(state.overdraw/10).toFixed(1)}×`;ui.compressionValue.value=`${state.compression}%`;ui.bytes.textContent=`${m.bytes.toFixed(1)} B`;ui.frameMetric.textContent=`${Math.round(m.mb)} MB`;ui.hitRate.textContent=`${Math.round(m.hit*100)}%`;ui.rate.textContent=`${m.rate.toFixed(1)} GB/s`;ui.strip.forEach(x=>x.classList.toggle("is-active",x.dataset.pattern===state.pattern));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(render);};[[ui.pattern,"change","pattern",String],[ui.targets,"input","targets",Number],[ui.samples,"input","samples",Number],[ui.overdraw,"input","overdraw",Number],[ui.compression,"input","compression",Number]].forEach(([e,n,k,c])=>e.addEventListener(n,()=>{state[k]=c(e.value);schedule();}));addEventListener("resize",schedule);render();}
