import { createPostprocessPass } from "../../render/postprocess.js?v=20260803-9";
import { resizeCanvasToDisplaySize } from "../../render/webgl.js?v=20260803-9";

const triangles=[[[ -1.08,-0.05],[-0.58,0.53],[-0.35,-0.30]],[[ -0.18,-0.26],[0.12,0.62],[0.48,-0.10]],[[0.55,-0.38],[0.90,0.48],[1.28,-0.08]]];
const boxes=[[[-1.12,-0.34],[-0.31,0.58]],[[-0.23,-0.31],[0.52,0.67]],[[0.50,-0.43],[1.32,0.53]]];
const origin=[0,-0.86];const state={stage:"result",targetX:22,targetY:58,depth:2};
function cross(a,b){return a[0]*b[1]-a[1]*b[0];}
function direction(){const v=[state.targetX/100-origin[0],state.targetY/100-origin[1]],l=Math.hypot(...v);return[v[0]/l,v[1]/l];}
function rayBox(d,box){let lo=0,hi=99;for(let axis=0;axis<2;axis++){if(Math.abs(d[axis])<1e-6){if(origin[axis]<box[0][axis]||origin[axis]>box[1][axis])return null;continue;}let a=(box[0][axis]-origin[axis])/d[axis],b=(box[1][axis]-origin[axis])/d[axis];if(a>b)[a,b]=[b,a];lo=Math.max(lo,a);hi=Math.min(hi,b);}return hi>=lo?lo:null;}
function rayTriangle(d,tri){let nearest=null;for(let i=0;i<3;i++){const a=tri[i],b=tri[(i+1)%3],v=[b[0]-a[0],b[1]-a[1]],den=cross(d,v);if(Math.abs(den)<1e-6)continue;const ao=[a[0]-origin[0],a[1]-origin[1]],t=cross(ao,v)/den,u=cross(ao,d)/den;if(t>=0&&u>=0&&u<=1&&(nearest===null||t<nearest))nearest=t;}return nearest;}
function trace(){const d=direction(),candidates=boxes.map((b,i)=>({i,t:rayBox(d,b)})).filter(x=>x.t!==null);let hit=-1,t=Infinity;candidates.forEach(({i})=>{const value=rayTriangle(d,triangles[i]);if(value!==null&&value<t){hit=i;t=value;}});return{boxes:Math.min(boxes.length,1+state.depth),candidates,hit,t:Number.isFinite(t)?t:null,d};}
const fragmentSource=`#version 300 es
precision highp float;
uniform vec2 uDirection; uniform int uHit; uniform int uStage; uniform float uDepth;
in vec2 vUv; out vec4 outColor;
float segment(vec2 p,vec2 a,vec2 b,float w){vec2 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.0,1.0);return 1.0-smoothstep(w,w+0.009,length(pa-ba*h));}
float boxLine(vec2 p,vec2 c,vec2 b){vec2 d=abs(p-c)-b;return 1.0-smoothstep(0.0,0.012,abs(max(d.x,d.y)));}
void main(){vec2 p=(vUv*2.0-1.0)*vec2(1.62,1.0);vec3 color=mix(vec3(0.02,0.033,0.036),vec3(0.075,0.09,0.09),vUv.y);vec2 grid=abs(fract((p+1.7)*6.0)-0.5);color+=step(0.487,max(grid.x,grid.y))*0.025;
  vec2 a0=vec2(-1.08,-0.05),a1=vec2(-0.58,0.53),a2=vec2(-0.35,-0.30);vec2 b0=vec2(-0.18,-0.26),b1=vec2(0.12,0.62),b2=vec2(0.48,-0.10);vec2 c0=vec2(0.55,-0.38),c1=vec2(0.90,0.48),c2=vec2(1.28,-0.08);
  float tris[3]=float[3](max(max(segment(p,a0,a1,0.014),segment(p,a1,a2,0.014)),segment(p,a2,a0,0.014)),max(max(segment(p,b0,b1,0.014),segment(p,b1,b2,0.014)),segment(p,b2,b0,0.014)),max(max(segment(p,c0,c1,0.014),segment(p,c1,c2,0.014)),segment(p,c2,c0,0.014)));
  vec2 centers[3]=vec2[3](vec2(-0.715,0.12),vec2(0.145,0.18),vec2(0.91,0.05));vec2 extents[3]=vec2[3](vec2(0.405,0.46),vec2(0.375,0.49),vec2(0.41,0.48));
  for(int i=0;i<3;i++){float outline=boxLine(p,centers[i],extents[i]);float enabled=i<int(uDepth+1.0)?1.0:0.0;if(uStage>=1)color=mix(color,vec3(0.25,0.58,0.82),outline*enabled*0.75);vec3 tc=i==uHit&&uStage==3?vec3(1.0,0.82,0.28):vec3(0.18,0.82,0.68);if(uStage>=2)color=mix(color,tc,tris[i]);}
  vec2 o=vec2(0.0,-0.86);vec2 end=o+uDirection*2.4;float ray=segment(p,o,end,0.008);color=mix(color,vec3(1.0,0.48,0.17),ray);float source=1.0-smoothstep(0.035,0.055,length(p-o));color=mix(color,vec3(1.0,0.90,0.46),source);outColor=vec4(pow(max(color,vec3(0)),vec3(1.0/2.2)),1.0);}`;
const ui={boxes:document.querySelector("#pickingBoxes"),canvas:document.querySelector("#pickingCanvas"),depth:document.querySelector("#pickingDepth"),depthValue:document.querySelector("#pickingDepthValue"),hit:document.querySelector("#pickingHit"),section:document.querySelector("#ray-picking"),stage:document.querySelector("#pickingStage"),strip:[...document.querySelectorAll(".picking-stage-strip [data-stage]")],t:document.querySelector("#pickingT"),targetX:document.querySelector("#pickingTargetX"),targetXValue:document.querySelector("#pickingTargetXValue"),targetY:document.querySelector("#pickingTargetY"),targetYValue:document.querySelector("#pickingTargetYValue"),triangles:document.querySelector("#pickingTriangles")};
class Renderer{constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl2",{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error("当前浏览器不支持 WebGL2。");this.pass=createPostprocessPass(this.gl,fragmentSource);this.loc={depth:this.gl.getUniformLocation(this.pass.program,"uDepth"),direction:this.gl.getUniformLocation(this.pass.program,"uDirection"),hit:this.gl.getUniformLocation(this.pass.program,"uHit"),stage:this.gl.getUniformLocation(this.pass.program,"uStage")};}render(s,result){const gl=this.gl,{width,height}=resizeCanvasToDisplaySize(this.canvas);this.pass.draw({configure:()=>{gl.uniform1f(this.loc.depth,s.depth);gl.uniform2fv(this.loc.direction,result.d);gl.uniform1i(this.loc.hit,result.hit);gl.uniform1i(this.loc.stage,{bvh:0,aabb:1,triangle:2,result:3}[s.stage]);},width,height});}}
function fail(message){ui.section?.classList.add("is-unavailable");const p=document.createElement("p");p.className="webgl-fallback";p.textContent=`射线拾取实验无法启动：${message}`;ui.canvas?.closest(".viewport-panel")?.prepend(p);}
export function initRayPickingLab(){if(!ui.canvas||!ui.stage)return;let renderer;try{renderer=new Renderer(ui.canvas);}catch(error){fail(error.message);return;}let frame=0;const render=()=>{frame=0;const result=trace();renderer.render(state,result);ui.targetXValue.value=`${state.targetX>=0?"+":""}${(state.targetX/100).toFixed(2)}`;ui.targetYValue.value=`${state.targetY>=0?"+":""}${(state.targetY/100).toFixed(2)}`;ui.depthValue.value=`${state.depth} 层`;ui.boxes.textContent=Math.min(7,1+state.depth*2);ui.triangles.textContent=result.candidates.length;ui.hit.textContent=result.hit<0?"无":`Triangle ${String.fromCharCode(65+result.hit)}`;ui.t.textContent=result.t===null?"—":result.t.toFixed(2);ui.strip.forEach(x=>x.classList.toggle("is-active",x.dataset.stage===state.stage));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(render);};[[ui.stage,"change","stage",String],[ui.targetX,"input","targetX",Number],[ui.targetY,"input","targetY",Number],[ui.depth,"input","depth",Number]].forEach(([e,n,k,c])=>e.addEventListener(n,()=>{state[k]=c(e.value);schedule();}));const point=e=>{const r=ui.canvas.getBoundingClientRect();state.targetX=Math.round((((e.clientX-r.left)/r.width)*2-1)*162);state.targetX=Math.max(-90,Math.min(90,state.targetX));state.targetY=Math.round((1-(e.clientY-r.top)/r.height)*200-100);state.targetY=Math.max(-20,Math.min(90,state.targetY));ui.targetX.value=state.targetX;ui.targetY.value=state.targetY;schedule();};ui.canvas.addEventListener("pointerdown",e=>{ui.canvas.setPointerCapture(e.pointerId);point(e);});ui.canvas.addEventListener("pointermove",e=>{if(ui.canvas.hasPointerCapture(e.pointerId))point(e);});addEventListener("resize",schedule);render();}
