import { createPostprocessPass } from "../../render/postprocess.js?v=20260803-10";
import { resizeCanvasToDisplaySize } from "../../render/webgl.js?v=20260803-10";

const fragmentSource=`#version 300 es
precision highp float;
uniform int uView; uniform float uDensity; uniform float uG; uniform float uSteps; uniform float uAngle;
in vec2 vUv; out vec4 outColor;
float noise3(vec3 p){return 0.5+0.5*sin(p.x*3.1+sin(p.z*4.3)+cos(p.y*5.7))*sin(p.y*2.7-p.z*3.4);}
void main(){vec2 p=(vUv*2.0-1.0)*vec2(1.62,1.0);vec3 scene=mix(vec3(0.018,0.028,0.035),vec3(0.08,0.10,0.12),vUv.y);float object=1.0-smoothstep(0.25,0.27,length(p-vec2(0.18,-0.18)));scene=mix(scene,vec3(0.055,0.07,0.075),object);vec2 source=vec2(-1.30,0.72),dir=normalize(vec2(cos(uAngle),sin(uAngle)));float trans=1.0,scatter=0.0,densityView=0.0;float cosTheta=0.72;float phase=(1.0-uG*uG)/(12.56637*pow(max(0.04,1.0+uG*uG-2.0*uG*cosTheta),1.5));
  for(int i=0;i<48;i++){if(float(i)>=uSteps)break;float z=(float(i)+0.5)/uSteps;vec2 sp=p+vec2(sin(z*7.0),cos(z*5.0))*0.025;float density=uDensity*(0.48+noise3(vec3(sp*1.4,z))*0.82);vec2 q=sp-source;float along=dot(q,dir),perp=abs(q.x*dir.y-q.y*dir.x);float beam=step(0.0,along)*(1.0-smoothstep(0.02+along*0.07,0.18+along*0.16,perp));float shadow=step(0.0,sp.x-0.18)*step(abs(sp.y+0.18),0.30);float stepSize=1.0/uSteps;scatter+=trans*density*beam*(1.0-shadow*0.86)*phase*stepSize*8.0;trans*=exp(-density*stepSize*2.2);densityView+=density*stepSize;}
  vec3 fog=vec3(0.24,0.72,0.82)*scatter;vec3 color=scene*trans+fog;if(uView==1)color=fog*1.4;else if(uView==2)color=vec3(trans);else if(uView==3)color=mix(vec3(0.04,0.08,0.11),vec3(0.94,0.50,0.18),clamp(densityView,0.0,1.0));float lamp=1.0-smoothstep(0.045,0.07,length(p-source));color=mix(color,vec3(1.0,0.86,0.52),lamp);outColor=vec4(pow(max(color,vec3(0)),vec3(1.0/2.2)),1.0);}`;
const state={view:"combined",density:28,anisotropy:52,steps:28,angle:-18};
const ui={angle:document.querySelector("#mediaLightAngle"),angleValue:document.querySelector("#mediaLightAngleValue"),anisotropy:document.querySelector("#mediaAnisotropy"),anisotropyValue:document.querySelector("#mediaAnisotropyValue"),canvas:document.querySelector("#mediaCanvas"),density:document.querySelector("#mediaDensity"),densityValue:document.querySelector("#mediaDensityValue"),phase:document.querySelector("#mediaPhase"),sampleMetric:document.querySelector("#mediaSampleMetric"),section:document.querySelector("#participating-media"),steps:document.querySelector("#mediaSteps"),stepsValue:document.querySelector("#mediaStepsValue"),strip:[...document.querySelectorAll(".media-term-strip [data-term]")],transmittance:document.querySelector("#mediaTransmittance"),view:document.querySelector("#mediaView")};
function phase(g){return(1-g*g)/(4*Math.PI*Math.pow(Math.max(.04,1+g*g-2*g*.72),1.5));}
class Renderer{constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl2",{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error("当前浏览器不支持 WebGL2。");this.pass=createPostprocessPass(this.gl,fragmentSource);this.loc={angle:this.gl.getUniformLocation(this.pass.program,"uAngle"),density:this.gl.getUniformLocation(this.pass.program,"uDensity"),g:this.gl.getUniformLocation(this.pass.program,"uG"),steps:this.gl.getUniformLocation(this.pass.program,"uSteps"),view:this.gl.getUniformLocation(this.pass.program,"uView")};}render(s,preview=false){const gl=this.gl,{width,height}=resizeCanvasToDisplaySize(this.canvas,preview?0.42:1);this.pass.draw({configure:()=>{gl.uniform1i(this.loc.view,{combined:0,scattering:1,transmittance:2,density:3}[s.view]);gl.uniform1f(this.loc.density,s.density/100);gl.uniform1f(this.loc.g,s.anisotropy/100);gl.uniform1f(this.loc.steps,s.steps);gl.uniform1f(this.loc.angle,s.angle*Math.PI/180);},width,height});}}
function fail(message){ui.section?.classList.add("is-unavailable");const p=document.createElement("p");p.className="webgl-fallback";p.textContent=`参与介质实验无法启动：${message}`;ui.canvas?.closest(".viewport-panel")?.prepend(p);}
export function initParticipatingMediaLab(){if(!ui.canvas||!ui.view)return;let renderer;try{renderer=new Renderer(ui.canvas);}catch(error){fail(error.message);return;}let frame=0,preview=false,settle=0;const render=()=>{frame=0;renderer.render(state,preview);const g=state.anisotropy/100;ui.densityValue.value=(state.density/100).toFixed(2);ui.anisotropyValue.value=`${g>=0?"+":""}${g.toFixed(2)}`;ui.stepsValue.value=state.steps;ui.angleValue.value=`${state.angle<0?"−":state.angle>0?"+":""}${Math.abs(state.angle)}°`;ui.transmittance.textContent=`${Math.round(Math.exp(-state.density/65)*100)}%`;ui.phase.textContent=phase(g).toFixed(2);ui.sampleMetric.textContent=`${state.steps} / ray`;ui.strip.forEach(x=>x.classList.toggle("is-active",x.dataset.term===state.view||state.view==="combined"));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(render);};const previewInput=()=>{preview=true;clearTimeout(settle);schedule();settle=setTimeout(()=>{preview=false;schedule();},180);};[[ui.view,"change","view",String],[ui.density,"input","density",Number],[ui.anisotropy,"input","anisotropy",Number],[ui.steps,"input","steps",Number],[ui.angle,"input","angle",Number]].forEach(([e,n,k,c])=>e.addEventListener(n,()=>{state[k]=c(e.value);previewInput();}));addEventListener("resize",()=>{preview=false;schedule();});render();}
