import { createPostprocessPass } from "../../render/postprocess.js?v=20260803-6";
import { resizeCanvasToDisplaySize } from "../../render/webgl.js?v=20260803-6";

const fragmentSource=`#version 300 es
precision highp float;
uniform float uDensity; uniform float uFov; uniform float uRange; uniform float uError; uniform int uMode;
in vec2 vUv; out vec4 outColor;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float line(float d,float w){return 1.0-smoothstep(w,w+0.008,abs(d));}
void main(){
  vec2 p=(vUv*2.0-1.0)*vec2(1.62,1.0);vec3 color=mix(vec3(0.025,0.04,0.04),vec3(0.085,0.11,0.105),vUv.y);
  vec2 cellSize=vec2(3.05/uDensity,1.72/(uDensity*0.72));vec2 cell=floor((p+vec2(1.52,0.78))/cellSize);vec2 center=(cell+0.5)*cellSize-vec2(1.52,0.78);center+=vec2(hash(cell)-0.5,hash(cell+7.3)-0.5)*cellSize*0.42;
  float object=1.0-smoothstep(0.035,0.055,length(p-center));float dist=length(center-vec2(0.0,-0.92));float halfWidth=max(0.01,(center.y+0.9)*uFov);float inFrustum=float(center.y>-0.82&&center.y<uRange&&abs(center.x)<halfWidth);
  float behindWall=float(center.y>0.04&&center.y<0.72&&center.x>-0.72&&center.x<0.18);float visible=uMode==0?1.0:inFrustum;if(uMode>=2)visible*=1.0-behindWall*0.78;float lowLod=float(uMode==3&&dist>(0.72+uError*0.03));
  vec3 objectColor=visible>0.4?mix(vec3(0.18,0.86,0.70),vec3(1.0,0.55,0.18),lowLod):vec3(0.18,0.23,0.23);color=mix(color,objectColor,object*(visible>0.4?1.0:0.48));
  float wall=step(-0.72,p.x)*step(p.x,0.18)*line(p.y-0.02,0.035);color=mix(color,vec3(0.60,0.67,0.65),wall*0.8);
  float wedge=abs(p.x)-(p.y+0.9)*uFov;float edge=(line(wedge,0.008)*step(-0.82,p.y)*step(p.y,uRange))+line(p.y-uRange,0.008)*step(abs(p.x),(p.y+0.9)*uFov);color=mix(color,vec3(0.28,0.72,0.95),edge*0.75);
  float camera=1.0-smoothstep(0.03,0.055,length(p-vec2(0.0,-0.9)));color=mix(color,vec3(1.0,0.86,0.42),camera);outColor=vec4(pow(max(color,vec3(0)),vec3(1.0/2.2)),1.0);
}`;
const state={mode:"lod",density:9,fov:58,distance:68,error:5};
const ui={canvas:document.querySelector("#cullingCanvas"),density:document.querySelector("#cullingDensity"),densityValue:document.querySelector("#cullingDensityValue"),distance:document.querySelector("#cullingDistance"),distanceValue:document.querySelector("#cullingDistanceValue"),error:document.querySelector("#cullingError"),errorValue:document.querySelector("#cullingErrorValue"),fov:document.querySelector("#cullingFov"),fovValue:document.querySelector("#cullingFovValue"),mode:document.querySelector("#cullingMode"),rate:document.querySelector("#cullingRate"),section:document.querySelector("#scene-culling"),strip:[...document.querySelectorAll(".culling-stage-strip [data-mode]")],total:document.querySelector("#cullingTotal"),triangles:document.querySelector("#cullingTriangles"),visible:document.querySelector("#cullingVisible")};
function model(){const total=state.density*Math.round(state.density*0.72);const frustum=Math.min(1,0.14+state.fov/150+state.distance/260);const factor={none:1,frustum:frustum,occlusion:frustum*0.74,lod:frustum*0.74}[state.mode];const visible=Math.max(1,Math.round(total*factor));const lodFactor=state.mode==="lod"?Math.max(0.18,0.62-state.error*0.028):1;return{total,visible,triangles:visible*18000*lodFactor};}
class Renderer{constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl2",{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error("当前浏览器不支持 WebGL2。");this.pass=createPostprocessPass(this.gl,fragmentSource);this.loc={density:this.gl.getUniformLocation(this.pass.program,"uDensity"),error:this.gl.getUniformLocation(this.pass.program,"uError"),fov:this.gl.getUniformLocation(this.pass.program,"uFov"),mode:this.gl.getUniformLocation(this.pass.program,"uMode"),range:this.gl.getUniformLocation(this.pass.program,"uRange")};}render(s){const gl=this.gl,{width,height}=resizeCanvasToDisplaySize(this.canvas);this.pass.draw({configure:()=>{gl.uniform1f(this.loc.density,s.density);gl.uniform1f(this.loc.fov,Math.tan(s.fov*Math.PI/360));gl.uniform1f(this.loc.range,-0.45+s.distance/70);gl.uniform1f(this.loc.error,s.error);gl.uniform1i(this.loc.mode,{none:0,frustum:1,occlusion:2,lod:3}[s.mode]);},width,height});}}
function fail(message){ui.section?.classList.add("is-unavailable");const p=document.createElement("p");p.className="webgl-fallback";p.textContent=`场景剔除实验无法启动：${message}`;ui.canvas?.closest(".viewport-panel")?.prepend(p);}
export function initSceneCullingLab(){if(!ui.canvas||!ui.mode)return;let renderer;try{renderer=new Renderer(ui.canvas);}catch(error){fail(error.message);return;}let frame=0;const render=()=>{frame=0;renderer.render(state);const m=model();ui.densityValue.value=`${state.density} × ${Math.round(state.density*0.72)}`;ui.fovValue.value=`${state.fov}°`;ui.distanceValue.value=`${state.distance} m`;ui.errorValue.value=`${state.error} px`;ui.total.textContent=m.total;ui.visible.textContent=m.visible;ui.rate.textContent=`${Math.round((1-m.visible/m.total)*100)}%`;ui.triangles.textContent=`${(m.triangles/1e6).toFixed(2)} M`;ui.strip.forEach(x=>x.classList.toggle("is-active",x.dataset.mode===state.mode));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(render);};[[ui.mode,"change","mode",String],[ui.density,"input","density",Number],[ui.fov,"input","fov",Number],[ui.distance,"input","distance",Number],[ui.error,"input","error",Number]].forEach(([e,n,k,c])=>e.addEventListener(n,()=>{state[k]=c(e.value);schedule();}));addEventListener("resize",schedule);render();}
